
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adi
 */
public class AddCurseFrame extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    private final MainFrame parent;
    /**
     * Creates new form AddCurseFrame
     */
     
    public AddCurseFrame(MainFrame parent) {
        this.parent = parent;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNume = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        lblTermenPlata = new javax.swing.JLabel();
        lblDataScadenta = new javax.swing.JLabel();
        lblIntarziere = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        txtRuta = new javax.swing.JTextField();
        txtTermePlata = new javax.swing.JTextField();
        data = new datechooser.beans.DateChooserCombo();
        txtScadenta = new javax.swing.JTextField();
        CurseBtnOk = new javax.swing.JButton();
        CurseBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));

        lblNume.setText("Nume");

        lblRuta.setText("Ruta");

        lblTermenPlata.setText("Termen plata");

        lblDataScadenta.setText("Data scadenta");

        lblIntarziere.setText("Intarziere");

        SimpleDateFormat datetype = new SimpleDateFormat("yyyy-MM-dd");
        data.setDateFormat(datetype);
        data.setCalendarPreferredSize(new java.awt.Dimension(350,350));
        data.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        data.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        data.setShowOneMonth(true);

        CurseBtnOk.setText("OK");
        CurseBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurseBtnOkActionPerformed(evt);
            }
        });

        CurseBtnCancel.setText("Anulați");
        CurseBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurseBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIntarziere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDataScadenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTermenPlata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRuta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTermePlata)
                            .addComponent(txtRuta)
                            .addComponent(txtNume)
                            .addComponent(txtScadenta))
                        .addGap(0, 246, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurseBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CurseBtnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNume)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTermenPlata)
                    .addComponent(txtTermePlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataScadenta)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntarziere)
                    .addComponent(txtScadenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurseBtnOk)
                    .addComponent(CurseBtnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CurseBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurseBtnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CurseBtnCancelActionPerformed

    private void CurseBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurseBtnOkActionPerformed
        String name = txtNume.getText();
        String ruta = txtRuta.getText();
        String termen_plata = txtTermePlata.getText();
        String date = data.getText();
        String late = txtScadenta.getText();
        String sql = "INSERT INTO CURSE(NUME,RUTA,TERMEN_PLATA,DATA_SCADENTA,INTARZIERE)"
                + "VALUES('" + name + "','" + ruta + "','" + termen_plata + "','" + date + "','" + late + "')";
        
        try{
           Class.forName("org.sqlite.JDBC");
           conn = DriverManager.getConnection("jdbc:sqlite:lista.db");
        }
        catch (SQLException | ClassNotFoundException err){
           JOptionPane.showMessageDialog(null, "Nu s-a putut conecta la baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        try{
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sql);
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Eroare la comunicarea cu baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        parent.curse_db();
        this.dispose();
    }//GEN-LAST:event_CurseBtnOkActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CurseBtnCancel;
    private javax.swing.JButton CurseBtnOk;
    private datechooser.beans.DateChooserCombo data;
    private javax.swing.JLabel lblDataScadenta;
    private javax.swing.JLabel lblIntarziere;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTermenPlata;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtScadenta;
    private javax.swing.JTextField txtTermePlata;
    // End of variables declaration//GEN-END:variables
}
