
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adi
 */
public class EditCurseFrame extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    public String id = "",nume,ruta,termenplata,scadenta,intarziere;   
    private final MainFrame parent;
    /**
     * Creates new form EditCurseFrame
     */
    public EditCurseFrame(MainFrame parent,String ID) {
        this.parent = parent;
        initComponents();
        get_from_db(ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNume = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        lblTermenPlata = new javax.swing.JLabel();
        lblDataScadenta = new javax.swing.JLabel();
        lblIntarziere = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dbNume = new javax.swing.JTextField();
        dbRuta = new javax.swing.JTextField();
        dbTermenPlata = new javax.swing.JTextField();
        dbDataScadenta = new javax.swing.JTextField();
        dbIntarziere = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 600));

        lblNume.setText("Nume");

        lblRuta.setText("Ruta");

        lblTermenPlata.setText("Termen plata");

        lblDataScadenta.setText("Data scadenta");

        lblIntarziere.setText("Zile intarziere");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        dbNume.setPreferredSize(new java.awt.Dimension(200, 30));

        dbRuta.setPreferredSize(new java.awt.Dimension(200, 30));

        dbTermenPlata.setPreferredSize(new java.awt.Dimension(200, 30));

        dbDataScadenta.setPreferredSize(new java.awt.Dimension(200, 30));

        dbIntarziere.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDataScadenta, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(lblIntarziere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTermenPlata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dbNume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dbTermenPlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbDataScadenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbIntarziere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNume)
                    .addComponent(dbNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta)
                    .addComponent(dbRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTermenPlata)
                    .addComponent(dbTermenPlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataScadenta)
                    .addComponent(dbDataScadenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntarziere)
                    .addComponent(dbIntarziere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        int option = -1;
        if (nume != dbNume.getText() && 
                ruta != dbRuta.getText() &&
                termenplata != dbTermenPlata.getText() &&
                scadenta != dbDataScadenta.getText() &&
                intarziere != dbIntarziere.getText()){
            String err = "Ati modificat datele despre " + nume + " \nDoriti sa salvati?";
            option = JOptionPane.showInternalConfirmDialog(rootPane, err,"",JOptionPane.YES_NO_OPTION);
        }
        System.out.println(option);
        if (option == 1){
            this.dispose();
        }
        else if(option == 0){
            try{
               Statement stmt =  conn.createStatement();
               String sql = "UPDATE CURSE "
                    + "SET NUME='" + dbNume.getText() + "',RUTA='" + dbRuta.getText() + "',"
                    + "TERMEN_PLATA='" + dbTermenPlata.getText() + "',DATA_SCADENTA='" + dbDataScadenta.getText() 
                       + "',INTARZIERE='" + dbIntarziere.getText() + "'"
                    + "WHERE ID=" + id;
               stmt.executeUpdate(sql);
               parent.curse_db();
               this.dispose();
            }
            catch (SQLException ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField dbDataScadenta;
    private javax.swing.JTextField dbIntarziere;
    private javax.swing.JTextField dbNume;
    private javax.swing.JTextField dbRuta;
    private javax.swing.JTextField dbTermenPlata;
    private javax.swing.JLabel lblDataScadenta;
    private javax.swing.JLabel lblIntarziere;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTermenPlata;
    // End of variables declaration//GEN-END:variables

    private void get_from_db(String ID) {
        try {
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:lista.db");
            String sql = "SELECT * FROM CURSE WHERE nume = '" + ID + "'";
            Statement stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            while (rs.next()){
                id = rs.getString("ID");
                nume = rs.getString("NUME");
                ruta = rs.getString("RUTA");
                termenplata = rs.getString("TERMEN_PLATA");
                scadenta = rs.getString("DATA_SCADENTA");
                intarziere = rs.getString("INTARZIERE");
            }
            dbNume.setText(nume);
            dbRuta.setText(ruta);
            dbTermenPlata.setText(termenplata);
            dbDataScadenta.setText(scadenta);
            dbIntarziere.setText(intarziere);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(EditCurseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
