
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adi
 */
public class EditFrame extends javax.swing.JFrame {
    public String id = "";
    public Connection conn;
    public ResultSet rs;
    public String nume = "";
    public String idbursa = "";
    public String  cui = "";
    public String regcomert = "";
    public String adresa = "";
    private final MainFrame parent;
    /**
     * Creates new form EditFrame
     */
    public EditFrame(MainFrame parent,String ID) {
        this.parent = parent;
        id = ID;
        try {
            connect_to_db();
            initComponents();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Nu s-a putut conecta la baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblIdBursa = new javax.swing.JLabel();
        lblCui = new javax.swing.JLabel();
        lblRegComert = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        dbName = new javax.swing.JTextField();
        dbIdBursa = new javax.swing.JTextField();
        dbCUI = new javax.swing.JTextField();
        dbRegComert = new javax.swing.JTextField();
        dbAdresa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lblName.setText("Nume");

        lblIdBursa.setText("Id bursa");

        lblCui.setText("CUI");

        lblRegComert.setText("Registrul comerțului");

        lblAdresa.setText("Adresă");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anulați");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRegComert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIdBursa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dbAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(dbRegComert)
                            .addComponent(dbCUI)
                            .addComponent(dbIdBursa)
                            .addComponent(dbName))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdBursa)
                    .addComponent(dbIdBursa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCui)
                    .addComponent(dbCUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegComert)
                    .addComponent(dbRegComert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresa)
                    .addComponent(dbAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void connect_to_db() throws SQLException{
       
        try{
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:lista.db");
        }
        catch (SQLException | ClassNotFoundException err){
            JOptionPane.showMessageDialog(null, "Nu s-a putut conecta la baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    } 
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        String sql = "SELECT * FROM FIRME where nume='" + id + "'";
        
        try {
            Statement stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                nume = rs.getString("NUME");
                idbursa = rs.getString("ID_BURSA");
                cui = rs.getString("CUI");
                regcomert = rs.getString("REGCOMERT");
                adresa = rs.getString("ADRESA");
            }
            dbName.setText(nume);
            dbIdBursa.setText(idbursa);
            dbCUI.setText(cui);
            dbRegComert.setText(regcomert);
            dbAdresa.setText(adresa);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Eroare la comunicarea cu baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int option = -1;
        String tmpname = dbName.getText();
        String tmpidbursa = dbIdBursa.getText();
        String tmpcui = dbCUI.getText();
        String tmpregcomert = dbRegComert.getText();
        String tmpadresa = dbAdresa.getText();
        if( tmpname != nume &&
                tmpidbursa != idbursa &&
                tmpcui != cui &&
                tmpregcomert != regcomert &&
                tmpadresa != adresa){
            String err = "Ati modificat datele despre" + id + "\nDoriti sa salvati?";
            option = JOptionPane.showInternalConfirmDialog(rootPane, err,"",JOptionPane.YES_NO_OPTION);
        }
        if (option == 1){
            this.dispose();
        }
        else if (option == 0){
            String getID = "SELECT ID from ADY.FIRME WHERE NUME='" + nume + "'";
            int actualID = 0;
            try{
                Statement stmt = conn.createStatement();
                ResultSet res = stmt.executeQuery(getID);
                while(res.next()){
                    actualID = res.getInt("ID");
                }
            }
            catch (SQLException err){
                System.out.println(err.getCause());
            }
            String sql = "UPDATE ADY.FIRME "
                    + "SET NUME='" + tmpname + "',ID_BURSA='" + tmpidbursa + "',"
                    + "CUI='" + tmpcui + "',REGCOMERT='" + tmpregcomert + "',ADRESA='" + tmpadresa + "'"
                    + "WHERE ID=" + actualID;
            System.out.println(sql);
            Statement stmt;
            try {
                stmt = conn.createStatement();
                stmt.executeUpdate(sql);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Eroare la comunicarea cu baza de date!", "Eroare", JOptionPane.ERROR_MESSAGE);
            }
        }
        parent.GetFromDB();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dbAdresa;
    private javax.swing.JTextField dbCUI;
    private javax.swing.JTextField dbIdBursa;
    private javax.swing.JTextField dbName;
    private javax.swing.JTextField dbRegComert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblCui;
    private javax.swing.JLabel lblIdBursa;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRegComert;
    // End of variables declaration//GEN-END:variables
}
